apiVersion: v1
kind: ConfigMap
metadata:
  name: spiffe-helper-config
  namespace: app
data:
  helper.conf: |
    agent_address = "/run/spire/agent-sockets/socket"
    cert_dir = "/run/spiffe"
    daemon_mode = true
    svid_file_name = "svid.pem"
    svid_key_file_name = "svid_key.pem"
    svid_bundle_file_name = "svid_bundle.pem"
    jwt_svid_file_mode = 0644
    jwt_svids = [{
      jwt_audience = "SPIFFE/074122282848:rds:db-RPRRV425HSYWZPCF3LXOCIDUVA:testuser"
      jwt_svid_file_name = "jwt/svid.jwt"
    }]
