apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmaps/spiffe-helper.yaml
  - configmaps/db-connect.yaml
  - rbac/serviceaccounts.yaml
  - deployments/test-workload.yaml
  - deployments/denied-workload.yaml
  - bypass-workload.yaml